# This file should only be editted from the template
name: Classroom Repo Init from Template

on:
  push:
    branches:
      - '**'
      - 'master'

permissions:
  checks: write
  actions: read
  contents: read
  issues: write

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: .github/template/cpissues.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
