# This file should only be editted from the template
name: Classroom Repo Init from Template

on:
  push:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: "Copy Issues from Template"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd .github/template/ \
          .github/template/cpissues.sh 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: .github/template/countissues.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

